# Generated by Django 4.2.2 on 2023-06-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientClerk', '0002_rename_name_patient_fname_patient_lname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='level',
            field=models.CharField(blank=True, choices=[('i', 'Intern'), ('m', 'Medical Practioner'), ('r', 'Registrar'), ('s', 'Specialist')], default='m', help_text='Your current level of specialisation', max_length=200),
        ),
    ]
